### Imports

Main documentation: https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM

In [15]:
import pandas as pd
import numpy as np
import ta
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import time
from datetime import datetime, timedelta

### API Connection and data downloading

## Constants

In [16]:
df = pd.read_csv("ETH_USD_1HR.csv")
df

          close       epoch      high        low       open
0     2052.5850  1701255600  2056.895  2045.5260  2048.0650
1     2053.7550  1701259200  2060.615  2050.1450  2052.5850
2     2053.6150  1701262800  2061.845  2051.7550  2053.7550
3     2036.4850  1701266400  2058.835  2032.4915  2053.3425
4     2031.3500  1701270000  2040.395  2020.2950  2036.2850
...         ...         ...       ...        ...        ...
4994  3323.4350  1719234000  3328.195  3291.3950  3317.9950
4995  3306.7450  1719237600  3331.734  3292.0050  3323.4350
4996  3278.6850  1719241200  3312.755  3260.6965  3307.2150
4997  3259.6875  1719244800  3291.445  3241.3980  3278.7950
4998  3292.5050  1719248400  3302.403  3245.0825  3258.7850

[4999 rows x 5 columns]

In [17]:
data_history = df.copy()
data_history

          close       epoch      high        low       open
0     2052.5850  1701255600  2056.895  2045.5260  2048.0650
1     2053.7550  1701259200  2060.615  2050.1450  2052.5850
2     2053.6150  1701262800  2061.845  2051.7550  2053.7550
3     2036.4850  1701266400  2058.835  2032.4915  2053.3425
4     2031.3500  1701270000  2040.395  2020.2950  2036.2850
...         ...         ...       ...        ...        ...
4994  3323.4350  1719234000  3328.195  3291.3950  3317.9950
4995  3306.7450  1719237600  3331.734  3292.0050  3323.4350
4996  3278.6850  1719241200  3312.755  3260.6965  3307.2150
4997  3259.6875  1719244800  3291.445  3241.3980  3278.7950
4998  3292.5050  1719248400  3302.403  3245.0825  3258.7850

[4999 rows x 5 columns]

## Feature Engineering
Here we introduce all the features we need (indicators, std, price action etc..)
* roc
* willims r indicator
* ATr
* cci
* stddev
* Aroon
* ema_9
* ema_20
* ema_50,
* ADX,
* RSI
* Candle size

### Trend Indicators
* EMA_9, EMA_20, EMA_50, Aroon indicator, adx indicator, cci indicator,

In [18]:
ema_9 = ta.trend.EMAIndicator(close=df['close'], window=9)
ema_20 = ta.trend.EMAIndicator(close=df['close'], window=20)
ema_50 = ta.trend.EMAIndicator(close=df['close'], window=50)
df = df.assign(ema_9 = ema_9.ema_indicator())
df = df.assign(ema_20 = ema_20.ema_indicator())
df = df.assign(ema_50 = ema_50.ema_indicator())
# aroon = ta.trend.AroonIndicator(high=df['high'], low=df['low'], window=14).aroon_indicator()
# df = df.assign(aroon=aroon)
adx = ta.trend.ADXIndicator(high=df['high'],low=df['low'], close=df['close'], window=14).adx()
df = df.assign(adx=adx)
# cci = ta.trend.CCIIndicator(high=df['high'], low=df['low'], close=df['close'], window=14).cci()
# df = df.assign(cci=cci)

### Momentum Indicators
* Rsi, candle size, ROC,Williams %r

In [19]:
true_candle_size = df['close'] - df['open']
df = df.assign(true_candle_size = true_candle_size)
candle_size = abs(df['close'] - df['open'])
df = df.assign(candle_size=candle_size)
rsi_value = ta.momentum.RSIIndicator(close=df['close'], window=14)
df = df.assign(rsi = rsi_value.rsi())
# roc = ta.momentum.ROCIndicator(close=df['close'], window=5).roc()
# df = df.assign(roc=roc)
# williams = ta.momentum.WilliamsRIndicator(high=df['high'], low=df['low'], close=df['close'], lbp=14).williams_r()
# df = df.assign(williams = williams)

## Volatility Indicators
* ATR indicator, BOllinger Bands Parameters,

In [20]:
candle_diff = np.where(df['close'] >= df['open'],
                       np.maximum(abs(df['open'] - df['low']), abs(df['high'] - df['close'])),
                       np.maximum(abs(df['high'] - df['open']), abs(df['close'] - df['low'])))
wick_ratio =candle_size / candle_diff
df = df.assign(wick_ratio = wick_ratio)

In [21]:
df

,close,epoch,high,low,open,ema_9,ema_20,ema_50,adx,true_candle_size,candle_size,rsi,wick_ratio
0,2052.5850,1701255600,2056.895,2045.5260,2048.0650,NaN,NaN,NaN,0.000000,4.5200,4.5200,NaN,1.048724
1,2053.7550,1701259200,2060.615,2050.1450,2052.5850,NaN,NaN,NaN,0.000000,1.1700,1.1700,NaN,0.170554
2,2053.6150,1701262800,2061.845,2051.7550,2053.7550,NaN,NaN,NaN,0.000000,-0.1400,0.1400,NaN,0.017305
3,2036.4850,1701266400,2058.835,2032.4915,2053.3425,NaN,NaN,NaN,0.000000,-16.8575,16.8575,NaN,3.069185
4,2031.3500,1701270000,2040.395,2020.2950,2036.2850,NaN,NaN,NaN,0.000000,-4.9350,4.9350,NaN,0.446404
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,3323.4350,1719234000,3328.195,3291.3950,3317.9950,3343.184033,3380.968287,3433.242135,64.330997,5.4400,5.4400,25.326321,0.204511
4995,3306.7450,1719237600,3331.734,3292.0050,3323.4350,3335.896226,3373.899402,3428.281463,65.129209,-16.6900,16.6900,22.814543,1.132293
4996,3278.6850,1719241200,3312.755,3260.6965,3307.2150,3324.453981,3364.831364,3422.414935,66.118811,-28.5300,28.5300,19.341466,1.586013
4997,3259.6875,1719244800,3291.445,3241.3980,3278.7950,3311.500685,3354.817663,3416.033467,67.167026,-19.1075,19.1075,17.409168,1.044725
4998,3292.5050,1719248400,3302.403,3245.0825,3258.7850,3307.701548,3348.883123,3411.189214,67.494243,33.7200,33.7200,30.353453,2.460865

In [22]:
atr = ta.volatility.AverageTrueRange(high=df['high'],
                                     low=df['low'], 
                                     close=df['close'],
                                     window=14).average_true_range()
df = df.assign(atr=atr)
bol_width = ta.volatility.BollingerBands(close=df['close'], window=20, window_dev=2).bollinger_wband()
df = df.assign(bol_width=bol_width)
bol_above = ta.volatility.BollingerBands(close=df['close'], window=20, window_dev=2).bollinger_hband_indicator()
df = df.assign(bol_above=bol_above)
bol_below = ta.volatility.BollingerBands(close=df['close'], window=20, window_dev=2).bollinger_lband_indicator()
df = df.assign(bol_below=bol_below)
# average_candle_size = df['candle_size'].rolling(window=14).mean()
# df = df.assign(average_candle_size = average_candle_size)

In [23]:
trend_filter = np.where((df['close'] >= df['ema_20']) & (df['ema_20'] >= df['ema_50']), 1,
                        np.where((df['close'] <= df['ema_20']) & (df['ema_20'] <= df['ema_50']), 0, 2))
df = df.assign(trend_filter = trend_filter)

In [24]:
immediate_trend = (df['close'] >= df['ema_9']).astype(int)
df = df.assign(immediate_trend = immediate_trend)

In [28]:
df[-30:]

,close,high,low,open,ema_9,ema_20,ema_50,adx,true_candle_size,candle_size,rsi,wick_ratio,atr,bol_width,bol_above,bol_below,trend_filter,immediate_trend
4969,3498.8350,3502.545,3494.6285,3496.8850,3501.352872,3502.306323,3504.837748,10.246313,1.9500,1.9500,47.462728,0.525606,11.335208,0.863424,0.0,0.0,0,0
4970,3496.4050,3503.085,3492.0050,3498.8350,3500.363298,3501.744293,3504.507052,10.565343,-2.4300,2.4300,45.934521,0.552273,11.316979,0.863647,0.0,0.0,0,0
4971,3483.4850,3497.995,3479.3890,3496.4050,3496.987638,3500.005312,3503.682658,11.961849,-12.9200,12.9200,38.784207,3.154297,11.837624,0.952745,0.0,1.0,0,0
4972,3472.9950,3488.406,3470.3450,3483.4020,3492.189110,3497.432902,3502.479220,13.869439,-10.4070,10.4070,34.137782,2.079736,12.282151,1.163512,0.0,1.0,0,0
4973,3461.5150,3481.195,3460.0050,3472.9950,3486.054288,3494.012149,3500.872780,16.214397,-11.4800,11.4800,29.914102,1.400000,12.918425,1.519402,0.0,1.0,0,0
4974,3471.6750,3478.865,3460.1950,3461.5150,3483.178431,3491.884802,3499.727769,18.391859,10.1600,10.1600,37.306948,1.413074,13.329252,1.662071,0.0,0.0,0,0
4975,3476.3250,3477.325,3470.6950,3471.6750,3481.807745,3490.402916,3498.810013,20.413788,4.6500,4.6500,40.405312,4.650000,12.850734,1.743019,0.0,0.0,0,0
4976,3478.8750,3480.655,3474.0050,3476.3250,3481.221196,3489.305019,3498.028248,21.767023,2.5500,2.5500,42.095358,1.099138,12.407825,1.797761,0.0,0.0,0,0
4977,3434.1350,3479.105,3407.6250,3478.8750,3471.803957,3484.050731,3495.522631,25.266694,-44.7400,44.7400,27.408771,1.687665,16.627266,2.341479,0.0,1.0,0,0
4978,3433.7750,3439.031,3405.7210,3434.1350,3464.198165,3479.262567,3493.101155,28.549269,-0.3600,0.3600,27.326157,0.012832,17.818890,2.723690,0.0,1.0,0,0
4979,3424.1705,3433.775,3411.6495,3433.7750,3456.192632,3474.015703,3490.397992,31.597375,-9.6045,9.6045,25.148286,0.767071,18.126505,3.093076,0.0,1.0,0,0
4980,3419.3750,3428.825,3416.4250,3424.3650,3448.829106,3468.811827,3487.612777,34.427759,-4.9900,4.9900,24.114853,1.118834,17.717469,3.365037,0.0,1.0,0,0
4981,3423.2850,3434.756,3409.2750,3419.3750,3443.720285,3464.475938,3485.090119,37.197326,3.9100,3.9100,26.757648,0.340860,18.272007,3.524666,0.0,0.0,0,0
4982,3422.8750,3426.865,3405.4550,3423.2850,3439.551228,3460.513944,3482.650310,39.841920,-0.4100,0.4100,26.652829,0.023536,18.496149,3.641003,0.0,0.0,0,0
4983,3403.0125,3427.815,3384.6635,3422.9250,3432.243482,3455.037616,3479.527259,42.633468,-19.9125,19.9125,22.130001,1.085209,20.257245,3.890880,0.0,0.0,0,0
4984,3401.5950,3419.995,3401.1850,3403.1535,3426.113786,3449.947843,3476.471092,45.225619,-1.5585,1.5585,21.845100,0.092539,20.153871,4.015493,0.0,0.0,0,0
4985,3406.1750,3412.635,3382.5850,3401.5950,3422.126029,3445.779001,3473.714382,47.872178,4.5800,4.5800,25.196026,0.240926,20.860737,4.048658,0.0,0.0,0,0
4986,3370.5850,3408.525,3352.7305,3406.1750,3411.817823,3438.617668,3469.670093,50.602782,-35.5900,35.5900,18.542812,1.993335,23.356006,4.384756,0.0,1.0,0,0
4987,3372.4250,3383.725,3363.1450,3370.5850,3403.939258,3432.313604,3465.856560,53.138342,1.8400,1.8400,19.723037,0.162832,23.157720,4.628401,0.0,0.0,0,0
4988,3367.6750,3382.835,3360.7850,3372.8410,3396.686407,3426.157546,3462.006302,55.512045,-5.1660,5.1660,18.959344,0.516910,23.078597,4.765790,0.0,0.0,0,0
4989,3383.2050,3392.995,3353.3250,3367.6750,3393.990125,3422.066828,3458.916055,56.617984,15.5300,15.5300,28.682438,1.082230,24.263697,4.641031,0.0,0.0,0,0
4990,3306.9950,3388.215,3217.1850,3383.2050,3376.591100,3411.107606,3452.958367,58.770884,-76.2100,76.2100,17.552924,0.848569,34.747005,5.273318,0.0,1.0,0,0
4991,3317.6285,3323.365,3302.8050,3306.9950,3364.798580,3402.204834,3447.651313,60.770006,10.6335,10.6335,22.095198,1.853656,33.733647,5.620542,0.0,0.0,0,0
4992,3319.3825,3330.395,3304.2550,3316.8285,3355.715364,3394.316993,3442.621164,62.205838,2.5540,2.5540,22.850239,0.203126,33.191244,5.861675,0.0,0.0,0,0
4993,3317.7450,3335.425,3310.0450,3319.3950,3348.121291,3387.024422,3437.724059,63.232754,-1.6500,1.6500,22.629732,0.102932,32.633298,6.066173,0.0,0.0,0,0
4994,3323.4350,3328.195,3291.3950,3317.9950,3343.184033,3380.968287,3433.242135,64.330997,5.4400,5.4400,25.326321,0.204511,32.930919,6.016045,0.0,0.0,0,0
4995,3306.7450,3331.734,3292.0050,3323.4350,3335.896226,3373.899402,3428.281463,65.129209,-16.6900,16.6900,22.814543,1.132293,33.416496,5.919135,0.0,0.0,0,0
4996,3278.6850,3312.755,3260.6965,3307.2150,3324.453981,3364.831364,3422.414935,66.118811,-28.5300,28.5300,19.341466,1.586013,34.748068,5.885943,0.0,0.0,0,0
4997,3259.6875,3291.445,3241.3980,3278.7950,3311.500685,3354.817663,3416.033467,67.167026,-19.1075,19.1075,17.409168,1.044725,35.840849,6.312871,0.0,0.0,0,0
4998,3292.5050,3302.403,3245.0825,3258.7850,3307.701548,3348.883123,3411.189214,67.494243,33.7200,33.7200,30.353453,2.460865,37.375110,6.266406,0.0,0.0,0,0

In [29]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,4989,4990,4991,4992,4993,4994,4995,4996,4997,4998
close,2052.585000,2053.755000,2053.615000,2036.485000,2031.350000,2025.925000,2032.445000,2037.283000,2038.550000,2025.695000,...,3383.205000,3306.995000,3317.628500,3319.382500,3317.745000,3323.435000,3306.745000,3278.685000,3259.687500,3292.505000
high,2056.895000,2060.615000,2061.845000,2058.835000,2040.395000,2033.825000,2037.705000,2037.845000,2042.095000,2039.881500,...,3392.995000,3388.215000,3323.365000,3330.395000,3335.425000,3328.195000,3331.734000,3312.755000,3291.445000,3302.403000
low,2045.526000,2050.145000,2051.755000,2032.491500,2020.295000,2019.145000,2020.035000,2028.275000,2032.832000,2019.395000,...,3353.325000,3217.185000,3302.805000,3304.255000,3310.045000,3291.395000,3292.005000,3260.696500,3241.398000,3245.082500
open,2048.065000,2052.585000,2053.755000,2053.342500,2036.285000,2031.455000,2025.925000,2032.625000,2037.275000,2038.475000,...,3367.675000,3383.205000,3306.995000,3316.828500,3319.395000,3317.995000,3323.435000,3307.215000,3278.795000,3258.785000
ema_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2039.330150,2036.603120,...,3393.990125,3376.591100,3364.798580,3355.715364,3348.121291,3343.184033,3335.896226,3324.453981,3311.500685,3307.701548
ema_20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3422.066828,3411.107606,3402.204834,3394.316993,3387.024422,3380.968287,3373.899402,3364.831364,3354.817663,3348.883123
ema_50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3458.916055,3452.958367,3447.651313,3442.621164,3437.724059,3433.242135,3428.281463,3422.414935,3416.033467,3411.189214
adx,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,56.617984,58.770884,60.770006,62.205838,63.232754,64.330997,65.129209,66.118811,67.167026,67.494243
true_candle_size,4.520000,1.170000,-0.140000,-16.857500,-4.935000,-5.530000,6.520000,4.658000,1.275000,-12.780000,...,15.530000,-76.210000,10.633500,2.554000,-1.650000,5.440000,-16.690000,-28.530000,-19.107500,33.720000
candle_size,4.520000,1.170000,0.140000,16.857500,4.935000,5.530000,6.520000,4.658000,1.275000,12.780000,...,15.530000,76.210000,10.633500,2.554000,1.650000,5.440000,16.690000,28.530000,19.107500,33.720000
rsi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.682438,17.552924,22.095198,22.850239,22.629732,25.326321,22.814543,19.341466,17.409168,30.353453
wick_ratio,1.048724,0.170554,0.017305,3.069185,0.446404,0.815634,1.106961,1.070805,0.286968,2.028571,...,1.082230,0.848569,1.853656,0.203126,0.102932,0.204511,1.132293,1.586013,1.044725,2.460865
atr,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,24.263697,34.747005,33.733647,33.191244,32.633298,32.930919,33.416496,34.748068,35.840849,37.375110
bol_width,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.641031,5.273318,5.620542,5.861675,6.066173,6.016045,5.919135,5.885943,6.312871,6.266406
bol_above,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
bol_below,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
trend_filter,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
immediate_trend,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [31]:
# del df['epoch']

In [32]:
dif = df.copy()
dif

,close,high,low,open,ema_9,ema_20,ema_50,adx,true_candle_size,candle_size,rsi,wick_ratio,atr,bol_width,bol_above,bol_below,trend_filter,immediate_trend
0,2052.5850,2056.895,2045.5260,2048.0650,NaN,NaN,NaN,0.000000,4.5200,4.5200,NaN,1.048724,0.000000,NaN,0.0,0.0,2,0
1,2053.7550,2060.615,2050.1450,2052.5850,NaN,NaN,NaN,0.000000,1.1700,1.1700,NaN,0.170554,0.000000,NaN,0.0,0.0,2,0
2,2053.6150,2061.845,2051.7550,2053.7550,NaN,NaN,NaN,0.000000,-0.1400,0.1400,NaN,0.017305,0.000000,NaN,0.0,0.0,2,0
3,2036.4850,2058.835,2032.4915,2053.3425,NaN,NaN,NaN,0.000000,-16.8575,16.8575,NaN,3.069185,0.000000,NaN,0.0,0.0,2,0
4,2031.3500,2040.395,2020.2950,2036.2850,NaN,NaN,NaN,0.000000,-4.9350,4.9350,NaN,0.446404,0.000000,NaN,0.0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,3323.4350,3328.195,3291.3950,3317.9950,3343.184033,3380.968287,3433.242135,64.330997,5.4400,5.4400,25.326321,0.204511,32.930919,6.016045,0.0,0.0,0,0
4995,3306.7450,3331.734,3292.0050,3323.4350,3335.896226,3373.899402,3428.281463,65.129209,-16.6900,16.6900,22.814543,1.132293,33.416496,5.919135,0.0,0.0,0,0
4996,3278.6850,3312.755,3260.6965,3307.2150,3324.453981,3364.831364,3422.414935,66.118811,-28.5300,28.5300,19.341466,1.586013,34.748068,5.885943,0.0,0.0,0,0
4997,3259.6875,3291.445,3241.3980,3278.7950,3311.500685,3354.817663,3416.033467,67.167026,-19.1075,19.1075,17.409168,1.044725,35.840849,6.312871,0.0,0.0,0,0
4998,3292.5050,3302.403,3245.0825,3258.7850,3307.701548,3348.883123,3411.189214,67.494243,33.7200,33.7200,30.353453,2.460865,37.375110,6.266406,0.0,0.0,0,0

In [16]:
# for column in dif.columns: # shift 1,2,3,4
#     num = list(range(1,duplicate_num+1))
#     new_columns = {}
#     for n in num:
#         new_column_name = f"{column}_{n}"
#         # Assign the shifted values to the new column name in the dictionary
#         new_columns[new_column_name] = df[column].shift(n)
#         df = df.assign(**new_columns)

In [33]:
df.tail()

,close,high,low,open,ema_9,ema_20,ema_50,adx,true_candle_size,candle_size,rsi,wick_ratio,atr,bol_width,bol_above,bol_below,trend_filter,immediate_trend
4994,3323.4350,3328.195,3291.3950,3317.995,3343.184033,3380.968287,3433.242135,64.330997,5.4400,5.4400,25.326321,0.204511,32.930919,6.016045,0.0,0.0,0,0
4995,3306.7450,3331.734,3292.0050,3323.435,3335.896226,3373.899402,3428.281463,65.129209,-16.6900,16.6900,22.814543,1.132293,33.416496,5.919135,0.0,0.0,0,0
4996,3278.6850,3312.755,3260.6965,3307.215,3324.453981,3364.831364,3422.414935,66.118811,-28.5300,28.5300,19.341466,1.586013,34.748068,5.885943,0.0,0.0,0,0
4997,3259.6875,3291.445,3241.3980,3278.795,3311.500685,3354.817663,3416.033467,67.167026,-19.1075,19.1075,17.409168,1.044725,35.840849,6.312871,0.0,0.0,0,0
4998,3292.5050,3302.403,3245.0825,3258.785,3307.701548,3348.883123,3411.189214,67.494243,33.7200,33.7200,30.353453,2.460865,37.375110,6.266406,0.0,0.0,0,0

## Calculate the target class

In [34]:
prediction_candles

-5

In [35]:
predicted_price = df['close'].shift(prediction_candles)
df = df.assign(predicted_price = predicted_price)
df = df.dropna()
target = np.where(
    df['predicted_price'] > (df['close'] + df['atr'] * candle_size_multiplier), 1,
    np.where(df['predicted_price'] < (df['close'] - df['atr'] * candle_size_multiplier), 0, 2)
)
del df['predicted_price']
df = df.assign(target=target)
df

,close,high,low,open,ema_9,ema_20,ema_50,adx,true_candle_size,candle_size,rsi,wick_ratio,atr,bol_width,bol_above,bol_below,trend_filter,immediate_trend,target
49,2087.1750,2094.3095,2083.7050,2092.2150,2088.752860,2076.621254,2060.523082,38.429923,-5.0400,5.0400,61.568690,1.452450,12.092792,4.610828,0.0,0.0,1,0,2
50,2080.4250,2091.0950,2076.8350,2087.1750,2087.087288,2076.983515,2061.303549,37.882113,-6.7500,6.7500,56.236051,1.721939,12.247593,4.363793,0.0,0.0,1,0,2
51,2078.0050,2082.8650,2073.7450,2080.4250,2085.270830,2077.080800,2061.958508,36.973599,-2.4200,2.4200,54.416318,0.568075,12.024193,4.058412,0.0,0.0,1,0,2
52,2079.4350,2082.8150,2070.3035,2078.0050,2084.103664,2077.305009,2062.643860,35.693355,1.4300,1.4300,55.336038,0.185678,12.059001,3.738749,0.0,0.0,1,0,2
53,2104.2450,2109.9700,2077.6550,2079.4350,2088.131931,2079.870723,2064.275278,36.200370,24.8100,24.8100,67.563891,4.333624,13.505858,3.536838,0.0,0.0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,3383.2050,3392.9950,3353.3250,3367.6750,3393.990125,3422.066828,3458.916055,56.617984,15.5300,15.5300,28.682438,1.082230,24.263697,4.641031,0.0,0.0,0,0,0
4990,3306.9950,3388.2150,3217.1850,3383.2050,3376.591100,3411.107606,3452.958367,58.770884,-76.2100,76.2100,17.552924,0.848569,34.747005,5.273318,0.0,1.0,0,0,2
4991,3317.6285,3323.3650,3302.8050,3306.9950,3364.798580,3402.204834,3447.651313,60.770006,10.6335,10.6335,22.095198,1.853656,33.733647,5.620542,0.0,0.0,0,0,0
4992,3319.3825,3330.3950,3304.2550,3316.8285,3355.715364,3394.316993,3442.621164,62.205838,2.5540,2.5540,22.850239,0.203126,33.191244,5.861675,0.0,0.0,0,0,0
4993,3317.7450,3335.4250,3310.0450,3319.3950,3348.121291,3387.024422,3437.724059,63.232754,-1.6500,1.6500,22.629732,0.102932,32.633298,6.066173,0.0,0.0,0,0,2

In [36]:
x = df.drop(['target'], axis =1)
y = df['target']

In [37]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [41]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4945 entries, 49 to 4993
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   close             4945 non-null   float64
 1   high              4945 non-null   float64
 2   low               4945 non-null   float64
 3   open              4945 non-null   float64
 4   ema_9             4945 non-null   float64
 5   ema_20            4945 non-null   float64
 6   ema_50            4945 non-null   float64
 7   adx               4945 non-null   float64
 8   true_candle_size  4945 non-null   float64
 9   candle_size       4945 non-null   float64
 10  rsi               4945 non-null   float64
 11  wick_ratio        4945 non-null   float64
 12  atr               4945 non-null   float64
 13  bol_width         4945 non-null   float64
 14  bol_above         4945 non-null   float64
 15  bol_below         4945 non-null   float64
 16  trend_filter      4945 non-null   int32
 17  immediate_trend   4945 non-null   int32
dtypes: float64(16), int32(2)
memory usage: 695.4 KB

In [40]:
y

49      2
50      2
51      2
52      2
53      0
       ..
4989    0
4990    2
4991    0
4992    0
4993    2
Name: target, Length: 4945, dtype: int32

In [46]:
x_scaled = scaler.fit(np.array(x))
x_scaled

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [44]:
y_scaled = scaler.fit_transform(np.array(y).reshape(-1,1))
y_scaled

array([[ 0.73150936],
       [ 0.73150936],
       [ 0.73150936],
       ...,
       [-1.81948767],
       [-1.81948767],
       [ 0.73150936]])

In [45]:
y_scaled.shape

(4945, 1)

In [38]:
# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [ ]:
X_scaled

In [ ]:
y = np.array(y)
y

In [ ]:
# Define sequence length
sequence_length = 10

# Create sequences and corresponding targets
def create_sequences(x, y, sequence_length):
    X_sequences, y_sequences = [], []
    for i in range(len(x) - sequence_length + 1):
        X_sequences.append(x[i:i + sequence_length])
        y_sequences.append(y[i + sequence_length - 1])  # target is the last element in the sequence
    return np.array(X_sequences), np.array(y_sequences)

X_seq, y_seq = create_sequences(X_scaled, y, sequence_length)

In [ ]:
from tensorflow.keras.utils import to_categorical

y_seq_categorical = to_categorical(y_seq)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_seq, y_seq_categorical, test_size=0.2, random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()
model.add(LSTM(50, input_shape=(sequence_length, X_scaled.shape[1]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(50, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(25, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
print(f'Test Accuracy: {accuracy}')

In [21]:
y_pred = model.predict(x_test)
acc = accuracy_score(y_test, y_pred)
acc

NameError: name 'model' is not defined